"""add ticket model

Revision ID: c1c0212c2102
Revises: de9d6b51a738
Create Date: 2026-08-04 15:37:13.837986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c0212c2102'
down_revision = 'de9d6b51a738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=16), nullable=False),
    sa.Column('room_layout', sa.JSON(), nullable=False),
    sa.Column('qa_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_ticket_number'), ['ticket_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_number'))

    op.drop_table('ticket')
    # ### end Alembic commands ###
